server:
    port: 6666

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://localhost:9411

    # We send request to member service to handle it
    cloud:
       gateway:
          routes:
            - id: member
              uri: lb://member
              predicates:
                - Path=/api/members/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true